import { useCallback, useEffect, useRef, useState } from 'react'
import type { Dispatch, MutableRefObject, SetStateAction } from 'react'
import { type ConnectionStatus, type WsClient } from '../ws'
import { now, normalizeToolArguments, type AssistantTurnEntry, type MessageVariant, type PendingScrollTarget, type Role, type StreamEntry, type SubTaskEntry, type TextEntry, type ToolApprovalEntry, type ToolApprovalState, type ToolCallPayload, type ToolEntry, type ToolProgressPayload, type ToolResultEntry, type ToolResultPayload, type TurnEndPayload } from '../appModel'

type UseMessagesArgs = { clientRef: MutableRefObject<WsClient | null>; connectionState: ConnectionStatus; sessionIdRef: MutableRefObject<string>; setRunning: Dispatch<SetStateAction<boolean>>; refreshSessions: () => Promise<void> }
type UseMessagesResult = {
  entries: StreamEntry[]; entriesRef: MutableRefObject<StreamEntry[]>; highlightedMessageId: number | null; setHighlightedMessageId: Dispatch<SetStateAction<number | null>>; highlightMessage: (messageId: number) => void; pendingScrollTarget: PendingScrollTarget; messagesEndRef: MutableRefObject<HTMLDivElement | null>; messageNodeRefs: MutableRefObject<Map<number, HTMLDivElement | null>>; registerMessageNode: (messageId: number) => (node: HTMLDivElement | null) => void; requestScrollToMessage: (target: PendingScrollTarget) => void; appendMessage: (role: Role, content: string, variant?: MessageVariant) => number; appendSystemMessage: (content: string, variant?: MessageVariant) => number; clearEntries: () => void; replaceEntries: (next: StreamEntry[]) => void; updateEntriesById: (entryId: number, updater: (entry: StreamEntry) => StreamEntry) => void; updateSubTaskEntry: (subId: string, updater: (entry: SubTaskEntry) => SubTaskEntry) => void; appendSubTaskEntry: (entry: Omit<SubTaskEntry, 'id' | 'kind'>) => number; beginTurn: () => void; trackCurrentTurnEntryId: (_entryId: number) => void; applyReplyFallback: (sessionId: string, turn: number | undefined, reply: string) => void; turnErrorNotifiedRef: MutableRefObject<boolean>; turnStats: TurnStat[]
}

/** 单轮统计（turn/end 通知里带来的增量，用于上下文面板的「每轮明细」）。 */
export type TurnStat = {
  turn: number
  totalTokens: number
  promptTokens: number
  completionTokens: number
  estimated: boolean
  elapsedMs: number
  toolCalls: number
  llmCalls: number
  time: string
}

const keyFor = (sessionId: string, turn: number): string => `${sessionId}:${turn}`
/** 已决 choice → 内联状态（once/session=放行；deny/空=拒绝；timeout=超时拒绝）。 */
const approvalStateOf = (choice: string): ToolApprovalState => (choice === 'timeout' ? 'timeout' : choice && choice !== 'deny' ? 'allowed' : 'denied')
const createMessage = (id: number, role: Role, content: string, variant: MessageVariant = 'default'): TextEntry => ({ id, kind: 'message', role, content, time: now(), variant })

export function useMessages({ clientRef, connectionState, sessionIdRef, setRunning, refreshSessions }: UseMessagesArgs): UseMessagesResult {
  const [entries, setEntries] = useState<StreamEntry[]>([])
  const entriesRef = useRef<StreamEntry[]>([])
  const [highlightedMessageId, setHighlightedMessageId] = useState<number | null>(null)
  const [pendingScrollTarget, setPendingScrollTarget] = useState<PendingScrollTarget>(null)
  const [turnStats, setTurnStats] = useState<TurnStat[]>([])
  const messagesEndRef = useRef<HTMLDivElement | null>(null)
  const messageNodeRefs = useRef(new Map<number, HTMLDivElement | null>())
  const highlightTimerRef = useRef<number | null>(null)
  const nextIdRef = useRef(0)
  const turnEntryIdsRef = useRef(new Map<string, number>())
  const turnErrorNotifiedRef = useRef(false)
  const commit = useCallback((next: StreamEntry[]): void => { entriesRef.current = next; nextIdRef.current = Math.max(nextIdRef.current, ...next.map((entry) => entry.id), 0); setEntries(next) }, [])
  const nextId = useCallback((): number => { nextIdRef.current += 1; return nextIdRef.current }, [])
  const findTurn = useCallback((sessionId: string, turn: number, source: StreamEntry[]): AssistantTurnEntry | undefined => { const id = turnEntryIdsRef.current.get(keyFor(sessionId, turn)); return source.find((entry): entry is AssistantTurnEntry => entry.kind === 'assistant-turn' && entry.id === id) }, [])
  const ensureTurn = useCallback((sessionId: string, turn: number, source: StreamEntry[]): [AssistantTurnEntry, StreamEntry[]] => { const existing = findTurn(sessionId, turn, source); if (existing) return [existing, source]; const entry: AssistantTurnEntry = { id: nextId(), kind: 'assistant-turn', sessionId, turn, body: '', bodyState: 'streaming', tools: [], time: now() }; turnEntryIdsRef.current.set(keyFor(sessionId, turn), entry.id); return [entry, [...source, entry]] }, [findTurn, nextId])
  const replaceTurn = useCallback((entry: AssistantTurnEntry, source: StreamEntry[]): void => commit(source.map((candidate) => candidate.id === entry.id ? entry : candidate)), [commit])
  const appendMessage = useCallback((role: Role, content: string, variant: MessageVariant = 'default'): number => { const id = nextId(); commit([...entriesRef.current, createMessage(id, role, content, variant)]); return id }, [commit, nextId])
  const appendSystemMessage = useCallback((content: string, variant: MessageVariant = 'default'): number => appendMessage('system', content, variant), [appendMessage])
  const replaceEntries = useCallback((next: StreamEntry[]): void => { turnEntryIdsRef.current.clear(); next.forEach((entry) => { if (entry.kind === 'assistant-turn') turnEntryIdsRef.current.set(keyFor(entry.sessionId, entry.turn), entry.id) }); setTurnStats([]); commit(next) }, [commit])
  const clearEntries = useCallback((): void => { turnEntryIdsRef.current.clear(); setTurnStats([]); commit([]) }, [commit])
  const updateEntriesById = useCallback((id: number, updater: (entry: StreamEntry) => StreamEntry): void => commit(entriesRef.current.map((entry) => entry.id === id ? updater(entry) : entry)), [commit])
  const updateSubTaskEntry = useCallback((subId: string, updater: (entry: SubTaskEntry) => SubTaskEntry): void => commit(entriesRef.current.map((entry) => entry.kind === 'subtask' && entry.subId === subId ? updater(entry) : entry)), [commit])
  const appendSubTaskEntry = useCallback((entry: Omit<SubTaskEntry, 'id' | 'kind'>): number => { const id = nextId(); commit([...entriesRef.current, { id, kind: 'subtask', ...entry }]); return id }, [commit, nextId])
  const beginTurn = useCallback((): void => { turnErrorNotifiedRef.current = false }, [])
  const trackCurrentTurnEntryId = useCallback((_entryId: number): void => {}, [])
  const requestScrollToMessage = useCallback((target: PendingScrollTarget): void => setPendingScrollTarget(target), [])
  const registerMessageNode = useCallback((id: number) => (node: HTMLDivElement | null): void => { if (node) messageNodeRefs.current.set(id, node); else messageNodeRefs.current.delete(id) }, [])
  const highlightMessage = useCallback((id: number): void => { setHighlightedMessageId(id); if (highlightTimerRef.current !== null) window.clearTimeout(highlightTimerRef.current); highlightTimerRef.current = window.setTimeout(() => { setHighlightedMessageId((current) => current === id ? null : current); highlightTimerRef.current = null }, 1800) }, [])
  const applyReplyFallback = useCallback((sessionId: string, turn: number | undefined, reply: string): void => { const resolvedTurn = Number(turn ?? 0); if (!reply || !resolvedTurn) return; const source = entriesRef.current.slice(); const [entry, next] = ensureTurn(sessionId, resolvedTurn, source); if (!entry.body) replaceTurn({ ...entry, body: reply, bodyState: 'completed' }, next) }, [ensureTurn, replaceTurn])

  useEffect(() => {
    const client = clientRef.current
    if (!client) return undefined
    client.onNotify('item/agentMessage/delta', (params) => { const sessionId = String(params.session_id ?? ''); const turn = Number(params.turn ?? 0); const delta = String(params.text ?? params.delta ?? ''); if (!sessionId || sessionId !== sessionIdRef.current || !turn || !delta) return; const source = entriesRef.current.slice(); const [entry, next] = ensureTurn(sessionId, turn, source); replaceTurn({ ...entry, body: entry.body + delta, bodyState: 'streaming' }, next) })
    client.onNotify('item/toolCall', (params) => { const payload = params as ToolCallPayload; const sessionId = String(payload.session_id ?? ''); const turn = Number(payload.turn ?? 0); if (!sessionId || sessionId !== sessionIdRef.current || !turn) return; const source = entriesRef.current.slice(); const [entry, next] = ensureTurn(sessionId, turn, source); const toolCallId = String(payload.tool_call_id ?? `${payload.name ?? 'tool'}:${entry.tools.length}`); if (entry.tools.some((tool) => tool.toolCallId === toolCallId)) return; const tool: ToolEntry = { id: nextId(), kind: 'tool', sessionId, toolCallId, name: String(payload.name ?? '未知工具'), toolArguments: normalizeToolArguments(payload.arguments), status: payload.status === 'blocked' ? 'blocked' : 'running', reason: payload.reason ? String(payload.reason) : undefined, progress: [{ time: now(), text: payload.status === 'blocked' ? '已被安全策略拦截' : '已开始执行' }], time: now() }; replaceTurn({ ...entry, tools: [...entry.tools, tool] }, next) })
    client.onNotify('item/toolProgress', (params) => { const payload = params as ToolProgressPayload; const sessionId = String(payload.session_id ?? ''); const turn = Number(payload.turn ?? 0); const toolCallId = String(payload.tool_call_id ?? ''); const text = String(payload.text ?? '').trim(); if (!sessionId || sessionId !== sessionIdRef.current || !turn || !toolCallId || !text) return; const entry = findTurn(sessionId, turn, entriesRef.current); if (!entry) return; replaceTurn({ ...entry, tools: entry.tools.map((tool) => tool.toolCallId === toolCallId ? { ...tool, progress: [...tool.progress, { time: now(), text }] } : tool) }, entriesRef.current) })
    client.onNotify('item/toolResult', (params) => { const payload = params as ToolResultPayload; const sessionId = String(payload.session_id ?? ''); const turn = Number(payload.turn ?? 0); if (!sessionId || sessionId !== sessionIdRef.current || !turn) return; const source = entriesRef.current.slice(); const [entry, next] = ensureTurn(sessionId, turn, source); const toolCallId = String(payload.tool_call_id ?? ''); const result: ToolResultEntry = { ok: Boolean(payload.ok), summary: String(payload.summary ?? ''), durationMs: Number(payload.duration_ms ?? 0), outputPreview: payload.output_preview === undefined ? undefined : String(payload.output_preview), outputBytes: payload.output_bytes === undefined ? undefined : Number(payload.output_bytes), truncated: Boolean(payload.truncated) }; const found = entry.tools.some((tool) => tool.toolCallId === toolCallId); const tools = found ? entry.tools.map((tool) => tool.toolCallId === toolCallId ? { ...tool, result } : tool) : [...entry.tools, { id: nextId(), kind: 'tool', sessionId, toolCallId: toolCallId || `unknown:${entry.tools.length}`, name: String(payload.name ?? '未知工具'), toolArguments: {}, status: 'running', result, progress: [], time: now() }]; replaceTurn({ ...entry, tools }, next) })
    client.onNotify('turn/end', (params) => { const payload = params as TurnEndPayload; const sessionId = String(payload.session_id ?? ''); const turn = Number(payload.turn ?? 0); if (sessionId && sessionId !== sessionIdRef.current) return; setRunning(false); const entry = sessionId && turn ? findTurn(sessionId, turn, entriesRef.current) : undefined; const error = String(payload.error ?? ''); if (entry) replaceTurn({ ...entry, bodyState: error ? 'error' : 'completed', traceId: String(payload.trace_id ?? '').trim() || undefined, error: error || undefined, elapsedMs: payload.elapsed_ms === undefined ? entry.elapsedMs : Number(payload.elapsed_ms), usage: payload.usage ?? entry.usage, llmCalls: payload.llm_calls === undefined ? entry.llmCalls : Number(payload.llm_calls) }, entriesRef.current); turnErrorNotifiedRef.current = Boolean(error); if (error) appendSystemMessage(`内核错误：${error}`, 'error'); if (turn) setTurnStats((current) => [...current.filter((item) => item.turn !== turn), { turn, totalTokens: Number(payload.usage?.total_tokens ?? 0), promptTokens: Number(payload.usage?.prompt_tokens ?? 0), completionTokens: Number(payload.usage?.completion_tokens ?? 0), estimated: Boolean(payload.usage?.estimated ?? true), elapsedMs: Number(payload.elapsed_ms ?? 0), toolCalls: Number(payload.tool_calls ?? 0), llmCalls: Number(payload.llm_calls ?? 0), time: now() }].sort((a, b) => a.turn - b.turn)); void refreshSessions() })
    client.onNotify('serverRequest/approval', (params) => { const sessionId = String(params.session_id ?? ''); const turn = Number(params.turn ?? 0); const toolCallId = String(params.tool_call_id ?? ''); if (!sessionId || sessionId !== sessionIdRef.current || !turn || !toolCallId) return; const source = entriesRef.current.slice(); const [entry, next] = ensureTurn(sessionId, turn, source); const rawOptions = Array.isArray(params.options) ? (params.options as Array<Record<string, unknown>>) : []; const approval: ToolApprovalEntry = { approvalId: String(params.approval_id ?? ''), code: String(params.code ?? ''), question: String(params.question ?? ''), command: String(params.command ?? ''), name: String(params.name ?? ''), options: rawOptions.map((item) => ({ value: String(item.value ?? ''), label: String(item.label ?? item.value ?? '') })), state: 'pending', timeoutMs: params.timeout_ms === undefined ? undefined : Number(params.timeout_ms) }; const exists = entry.tools.some((tool) => tool.toolCallId === toolCallId); const tools = exists ? entry.tools.map((tool) => tool.toolCallId === toolCallId ? { ...tool, approval } : tool) : [...entry.tools, { id: nextId(), kind: 'tool' as const, sessionId, toolCallId, name: String(params.name ?? '工具'), toolArguments: normalizeToolArguments(params.arguments), status: 'running' as const, progress: [{ time: now(), text: '等待审批' }], time: now(), approval }]; replaceTurn({ ...entry, tools }, next) })
    client.onNotify('item/approvalResolved', (params) => { const sessionId = String(params.session_id ?? ''); const turn = Number(params.turn ?? 0); const toolCallId = String(params.tool_call_id ?? ''); if (!sessionId || sessionId !== sessionIdRef.current || !turn || !toolCallId) return; const entry = findTurn(sessionId, turn, entriesRef.current); if (!entry) return; const choice = String(params.choice ?? ''); const decidedAt = Number(params.decided_at ?? 0) || undefined; const waitedMs = params.waited_ms === undefined ? undefined : Number(params.waited_ms); replaceTurn({ ...entry, tools: entry.tools.map((tool) => tool.toolCallId === toolCallId && tool.approval ? { ...tool, approval: { ...tool.approval, state: approvalStateOf(choice), choice, decidedAt, waitedMs } } : tool) }, entriesRef.current) })
    return undefined
  }, [appendSystemMessage, clientRef, ensureTurn, findTurn, nextId, refreshSessions, replaceTurn, sessionIdRef, setRunning])
  useEffect(() => { if (connectionState !== 'connected') setRunning(false) }, [connectionState, setRunning])
  useEffect(() => () => { if (highlightTimerRef.current !== null) window.clearTimeout(highlightTimerRef.current) }, [])
  return { entries, entriesRef, highlightedMessageId, setHighlightedMessageId, highlightMessage, pendingScrollTarget, messagesEndRef, messageNodeRefs, registerMessageNode, requestScrollToMessage, appendMessage, appendSystemMessage, clearEntries, replaceEntries, updateEntriesById, updateSubTaskEntry, appendSubTaskEntry, beginTurn, trackCurrentTurnEntryId, applyReplyFallback, turnErrorNotifiedRef, turnStats }
}
